#!/bin/bash
# Clears the cmake cache
# Author: Nicolas Perrenoud <nicolape@ee.ethz.ch>
# Co-Author: Nicolas Schlumberger <nico_at_orxonox.net>

find . -name "CMakeCache.txt" -exec rm -f {} \;
find . -name "cmake_install.cmake" -exec rm -f {} \;
find . -name "CMakeFiles" -exec rm -fr {} \;
find . -name "Makefile" -exec rm -fr {} \;

echo "Cmake Cache cleared!"
