char                 var0('a');
COUT(0) << "Creating variable of type 'char                '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var0)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var0)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var0)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var0)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var0)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var0)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var0)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var0)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var0)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var0)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var0)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var0)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var0)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var0)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var0)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var0)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var0)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var0)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var0)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var0)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var0)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var0)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var0)) << std::endl;

unsigned char        var1(42);
COUT(0) << "Creating variable of type 'unsigned char       '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var1)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var1)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var1)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var1)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var1)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var1)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var1)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var1)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var1)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var1)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var1)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var1)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var1)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var1)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var1)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var1)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var1)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var1)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var1)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var1)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var1)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var1)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var1)) << std::endl;

short                var2(-42);
COUT(0) << "Creating variable of type 'short               '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var2)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var2)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var2)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var2)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var2)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var2)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var2)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var2)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var2)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var2)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var2)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var2)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var2)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var2)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var2)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var2)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var2)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var2)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var2)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var2)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var2)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var2)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var2)) << std::endl;

unsigned short       var3(42);
COUT(0) << "Creating variable of type 'unsigned short      '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var3)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var3)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var3)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var3)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var3)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var3)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var3)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var3)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var3)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var3)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var3)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var3)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var3)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var3)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var3)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var3)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var3)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var3)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var3)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var3)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var3)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var3)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var3)) << std::endl;

int                  var4(-42);
COUT(0) << "Creating variable of type 'int                 '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var4)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var4)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var4)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var4)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var4)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var4)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var4)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var4)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var4)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var4)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var4)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var4)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var4)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var4)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var4)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var4)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var4)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var4)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var4)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var4)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var4)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var4)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var4)) << std::endl;

unsigned int         var5(42);
COUT(0) << "Creating variable of type 'unsigned int        '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var5)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var5)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var5)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var5)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var5)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var5)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var5)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var5)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var5)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var5)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var5)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var5)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var5)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var5)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var5)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var5)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var5)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var5)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var5)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var5)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var5)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var5)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var5)) << std::endl;

long                 var6(-42);
COUT(0) << "Creating variable of type 'long                '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var6)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var6)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var6)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var6)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var6)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var6)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var6)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var6)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var6)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var6)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var6)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var6)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var6)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var6)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var6)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var6)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var6)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var6)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var6)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var6)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var6)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var6)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var6)) << std::endl;

unsigned long        var7(42);
COUT(0) << "Creating variable of type 'unsigned long       '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var7)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var7)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var7)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var7)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var7)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var7)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var7)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var7)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var7)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var7)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var7)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var7)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var7)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var7)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var7)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var7)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var7)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var7)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var7)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var7)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var7)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var7)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var7)) << std::endl;

long long            var8(-42);
COUT(0) << "Creating variable of type 'long long           '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var8)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var8)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var8)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var8)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var8)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var8)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var8)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var8)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var8)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var8)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var8)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var8)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var8)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var8)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var8)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var8)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var8)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var8)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var8)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var8)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var8)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var8)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var8)) << std::endl;

unsigned long long   var9(42);
COUT(0) << "Creating variable of type 'unsigned long long  '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var9)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var9)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var9)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var9)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var9)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var9)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var9)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var9)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var9)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var9)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var9)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var9)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var9)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var9)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var9)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var9)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var9)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var9)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var9)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var9)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var9)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var9)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var9)) << std::endl;

float                var10(-42.0f);
COUT(0) << "Creating variable of type 'float               '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var10)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var10)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var10)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var10)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var10)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var10)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var10)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var10)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var10)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var10)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var10)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var10)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var10)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var10)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var10)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var10)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var10)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var10)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var10)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var10)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var10)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var10)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var10)) << std::endl;

double               var11(-42.0);
COUT(0) << "Creating variable of type 'double              '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var11)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var11)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var11)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var11)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var11)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var11)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var11)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var11)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var11)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var11)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var11)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var11)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var11)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var11)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var11)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var11)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var11)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var11)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var11)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var11)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var11)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var11)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var11)) << std::endl;

long double          var12(-42.0);
COUT(0) << "Creating variable of type 'long double         '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var12)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var12)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var12)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var12)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var12)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var12)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var12)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var12)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var12)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var12)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var12)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var12)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var12)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var12)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var12)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var12)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var12)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var12)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var12)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var12)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var12)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var12)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var12)) << std::endl;

bool                 var13(true);
COUT(0) << "Creating variable of type 'bool                '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var13)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var13)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var13)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var13)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var13)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var13)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var13)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var13)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var13)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var13)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var13)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var13)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var13)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var13)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var13)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var13)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var13)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var13)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var13)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var13)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var13)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var13)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var13)) << std::endl;

void*                var14(0);
COUT(0) << "Creating variable of type 'void*               '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var14)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var14)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var14)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var14)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var14)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var14)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var14)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var14)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var14)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var14)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var14)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var14)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var14)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var14)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var14)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var14)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var14)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var14)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var14)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var14)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var14)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var14)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var14)) << std::endl;

std::string          var15("aString");
COUT(0) << "Creating variable of type 'std::string         '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var15)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var15)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var15)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var15)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var15)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var15)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var15)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var15)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var15)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var15)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var15)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var15)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var15)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var15)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var15)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var15)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var15)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var15)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var15)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var15)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var15)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var15)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var15)) << std::endl;

orxonox::Vector2     var16(1,2);
COUT(0) << "Creating variable of type 'orxonox::Vector2    '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var16)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var16)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var16)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var16)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var16)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var16)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var16)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var16)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var16)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var16)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var16)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var16)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var16)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var16)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var16)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var16)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var16)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var16)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var16)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var16)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var16)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var16)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var16)) << std::endl;

orxonox::Vector3     var17(1,2,3);
COUT(0) << "Creating variable of type 'orxonox::Vector3    '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var17)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var17)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var17)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var17)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var17)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var17)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var17)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var17)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var17)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var17)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var17)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var17)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var17)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var17)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var17)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var17)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var17)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var17)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var17)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var17)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var17)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var17)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var17)) << std::endl;

orxonox::Vector4     var18(1,2,3,4);
COUT(0) << "Creating variable of type 'orxonox::Vector4    '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var18)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var18)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var18)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var18)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var18)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var18)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var18)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var18)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var18)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var18)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var18)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var18)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var18)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var18)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var18)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var18)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var18)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var18)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var18)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var18)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var18)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var18)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var18)) << std::endl;

orxonox::ColourValue var19(0,1,0,1);
COUT(0) << "Creating variable of type 'orxonox::ColourValue'." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var19)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var19)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var19)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var19)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var19)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var19)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var19)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var19)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var19)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var19)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var19)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var19)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var19)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var19)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var19)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var19)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var19)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var19)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var19)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var19)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var19)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var19)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var19)) << std::endl;

orxonox::Quaternion  var20(1,1,1,1);
COUT(0) << "Creating variable of type 'orxonox::Quaternion '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var20)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var20)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var20)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var20)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var20)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var20)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var20)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var20)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var20)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var20)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var20)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var20)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var20)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var20)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var20)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var20)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var20)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var20)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var20)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var20)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var20)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var20)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var20)) << std::endl;

orxonox::Radian      var21(-1.2);
COUT(0) << "Creating variable of type 'orxonox::Radian     '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var21)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var21)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var21)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var21)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var21)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var21)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var21)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var21)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var21)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var21)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var21)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var21)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var21)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var21)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var21)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var21)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var21)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var21)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var21)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var21)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var21)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var21)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var21)) << std::endl;

orxonox::Degree      var22(-42.0);
COUT(0) << "Creating variable of type 'orxonox::Degree     '." << std::endl;
COUT(0) << "To 'char                ': " << conversion_cast<std::string>(conversion_cast<char                >(var22)) << std::endl;
COUT(0) << "To 'unsigned char       ': " << conversion_cast<std::string>(conversion_cast<unsigned char       >(var22)) << std::endl;
COUT(0) << "To 'short               ': " << conversion_cast<std::string>(conversion_cast<short               >(var22)) << std::endl;
COUT(0) << "To 'unsigned short      ': " << conversion_cast<std::string>(conversion_cast<unsigned short      >(var22)) << std::endl;
COUT(0) << "To 'int                 ': " << conversion_cast<std::string>(conversion_cast<int                 >(var22)) << std::endl;
COUT(0) << "To 'unsigned int        ': " << conversion_cast<std::string>(conversion_cast<unsigned int        >(var22)) << std::endl;
COUT(0) << "To 'long                ': " << conversion_cast<std::string>(conversion_cast<long                >(var22)) << std::endl;
COUT(0) << "To 'unsigned long       ': " << conversion_cast<std::string>(conversion_cast<unsigned long       >(var22)) << std::endl;
COUT(0) << "To 'long long           ': " << conversion_cast<std::string>(conversion_cast<long long           >(var22)) << std::endl;
COUT(0) << "To 'unsigned long long  ': " << conversion_cast<std::string>(conversion_cast<unsigned long long  >(var22)) << std::endl;
COUT(0) << "To 'float               ': " << conversion_cast<std::string>(conversion_cast<float               >(var22)) << std::endl;
COUT(0) << "To 'double              ': " << conversion_cast<std::string>(conversion_cast<double              >(var22)) << std::endl;
COUT(0) << "To 'long double         ': " << conversion_cast<std::string>(conversion_cast<long double         >(var22)) << std::endl;
COUT(0) << "To 'bool                ': " << conversion_cast<std::string>(conversion_cast<bool                >(var22)) << std::endl;
COUT(0) << "To 'void*               ': " << conversion_cast<std::string>(conversion_cast<void*               >(var22)) << std::endl;
COUT(0) << "To 'std::string         ': " << conversion_cast<std::string>(conversion_cast<std::string         >(var22)) << std::endl;
COUT(0) << "To 'orxonox::Vector2    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector2    >(var22)) << std::endl;
COUT(0) << "To 'orxonox::Vector3    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector3    >(var22)) << std::endl;
COUT(0) << "To 'orxonox::Vector4    ': " << conversion_cast<std::string>(conversion_cast<orxonox::Vector4    >(var22)) << std::endl;
COUT(0) << "To 'orxonox::ColourValue': " << conversion_cast<std::string>(conversion_cast<orxonox::ColourValue>(var22)) << std::endl;
COUT(0) << "To 'orxonox::Quaternion ': " << conversion_cast<std::string>(conversion_cast<orxonox::Quaternion >(var22)) << std::endl;
COUT(0) << "To 'orxonox::Radian     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Radian     >(var22)) << std::endl;
COUT(0) << "To 'orxonox::Degree     ': " << conversion_cast<std::string>(conversion_cast<orxonox::Degree     >(var22)) << std::endl;

