#!/bin/bash
# Clears the cmake cache
# Author: Nicolas Perrenoud <nicolape@ee.ethz.ch>

find . -name "CMakeCache.txt" -exec rm -f {} \;
find . -name "cmake_install" -exec rm -f {} \;
find . -name "CMakeFiles" -exec rm -fr {} \;
find . -name "Makefile*" -exec rm -fr {} \;

echo "Cmake Cache cleared!"
