# Find GGZ

FIND_PATH(GGZ_INCLUDE_DIR ggzmod.h)

FIND_LIBRARY(GGZMOD_LIBRARY NAMES ggzmod)

# handle the QUIETLY and REQUIRED arguments and set GGZMOD_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GGZMOD DEFAULT_MSG GGZMOD_LIBRARY GGZ_INCLUDE_DIR)

IF(GGZMOD_FOUND)
  SET(GGZMOD_LIBRARIES ${GGZMOD_LIBRARY})
ENDIF(GGZMOD_FOUND)

MARK_AS_ADVANCED(GGZMOD_LIBRARY GGZMOD_LIBRARIES GGZ_INCLUDE_DIR)
