#!/bin/bash
# Clears the cmake cache
# Author: Nicolas Perrenoud <nicolape@ee.ethz.ch>

find . -iname "cmakecache*" -exec rm -f {} \;
find . -iname "cmake_ins*" -exec rm -f {} \;
find . -iname "cmakefiles*" -exec rm -fr {} \;
find . -iname "Makefile*" -exec rm -fr {} \;

echo "Cmake Cache cleared!"
